# Generated by Django 3.2 on 2023-06-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='country_name')),
                ('country_code', models.CharField(max_length=3, unique=True, verbose_name='country_code')),
            ],
            options={
                'db_table': 'country',
            },
        ),
    ]
